return {
    id = "loot_block",
    width = 1,
    height = 1,
    background = {},
    foreground = { { dx = 0, dy = 0, tileId = 76 } },
    overlay = {},
    colliders = { { dx = 0, dy = 0, mask = 15 } },
    interactors = { { dx = 0, dy = 0 } },
    on_interact = { "loot:basic_crate" },
    interact_range = 2.5,
    frequency = 1.0,
    max_per_map = 999,
    min_distance = 0,
    player_buildable = false,
}
