name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y zip npm lua5.1 love
          sudo npm install -g love.js

      - name: Create .love file
        run: zip -r -9 lua.love . -x ".git/*" ".github/*"

      - name: Convert to love.js
        run: |
          love.js lua.love dist -t cropbots

      - name: Prepare build
        run: |
          cp server.js dist/
          cd dist
          npm init -y
          npm i express

      - name: Add Service Worker
        run: |
          cp coi-serviceworker.js dist/
          sed -i 's/<head>/<head><script src="coi-serviceworker.js"><\/script>/' dist/index.html

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist'

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
